Update weaeaemain.yml

diff --git a/.github/workflows/weaeaemain.yml b/.github/workflows/weaeaemain.yml
--- a/.github/workflows/weaeaemain.yml
+++ b/.github/workflows/weaeaemain.yml
@@ -99,15 +99,39 @@ jobs:
       - name: Apply KSU Hooks
         run: |
           echo "Changing to configuration directory: $CONFIG..."
-          cd "$CONFIG"
-          # Apply additional patch
-          cp ../kernel_patches/ksu_hooks.patch ./
-          patch -p1 -fuzz 3  < ./ksu_hooks.patch
-          if [ $? -ne 0 ]; then
-            echo "ERROR: Failed to apply ksu_hooks.patch!"
-            cat ksu_hooks.patch # print the patch for review
+
+          if [! -d "$CONFIG" ]; then  # Check if $CONFIG is a directory
+            echo "ERROR: $CONFIG is not a directory!"
             exit 1
           fi
+
+          cd "$CONFIG"
+
+          PATCH_FILE="../kernel_patches/ksu_hooks.patch" # Store path in a variable
+
+          if [! -f "$PATCH_FILE" ]; then
+              echo "ERROR: $PATCH_FILE file not found!"
+              exit 1
+          fi
+
+          # ***Check for +++ and --- lines in the patch***
+          if grep -q '^\+\+\+' "$PATCH_FILE" && grep -q '^---' "$PATCH_FILE"; then
+              echo "Patch file contains +++ and --- lines. Proceeding..."
+          else
+              echo "ERROR: $PATCH_FILE is missing +++ or --- lines!"
+              cat "$PATCH_FILE"  # Show the patch contents
+              exit 1
+          fi
+
+
+          if! patch -p1 -fuzz 3 <"$PATCH_FILE"; then
+              echo "ERROR: Failed to apply $PATCH_FILE!"
+              patch -p1 -fuzz 3 <"$PATCH_FILE" 2>&1 | tee patch_error.log  # Capture and log errors
+              cat "$PATCH_FILE"
+              exit 1
+          fi
+
+          echo "$PATCH_FILE applied successfully."
 
       - name: Apply Hide Stuff Patches
         run: |
